version: "3.7"
name: ichat-go-dev
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ichat
      MYSQL_USER: ichat
      MYSQL_PASSWORD: ichat
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:7
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"